
services:
  app:
    build: .
    image: laravel12-app
    container_name: laravel12_app
    restart: unless-stopped
    # Run container processes as www-data so they match typical host file ownership for web files.
    # This avoids permission denied when host files are owned by UID/GID 33.
    user: "33:33"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./vendor:/var/www/html/vendor
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
    networks:
      - laravel

  web:
    image: nginx:1.25-alpine
    container_name: laravel12_web
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
